name: "Pull Request Check CI"

on: [ push, pull_request ]

jobs:
  build:
    name: NodeJS CI
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"
      - name: Lint code
        run: npm run lint
      - name: Run tests
        run: npm test
        env:
          CI: true
