name: "Deploy"
env:
  SAMPLE_ENV: "value"
on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint Dockerfile
        uses: brpaz/hadolint-action@master
        with:
          dockerfile: "Dockerfile"

      # Add more steps for your use case
